import path from 'node:path';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import { bundle } from '@remotion/bundler';
import { renderMedia, renderStill, selectComposition } from '@remotion/renderer';

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, '..');
const sceneFile = path.join(projectRoot, 'examples', 'audio-ducking-scene.tsx');
const generatedDir = path.join(here, '.generated');
const publicAudioDir = path.join(here, 'public', 'audio');
const outDir = path.join(here, 'out');

const STILL_FRAMES = [45, 90];

for (const dir of [generatedDir, publicAudioDir, outDir]) mkdirSync(dir, { recursive: true });
if (!existsSync(sceneFile)) throw new Error(`Scene not found: ${sceneFile}`);

/**
 * Генерирует PCM WAV (16-bit mono) без внешних зависимостей, чтобы e2e-рендер
 * аудио не требовал сети и бинарных ассетов в репозитории.
 */
function createToneWav({ durationSeconds, frequency, sampleRate = 22050 }) {
  const numSamples = Math.floor(durationSeconds * sampleRate);
  const dataSize = numSamples * 2;
  const buffer = Buffer.alloc(44 + dataSize);

  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(1, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(sampleRate * 2, 28);
  buffer.writeUInt16LE(2, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);

  for (let i = 0; i < numSamples; i += 1) {
    const t = i / sampleRate;
    // Плавное затухание по краям, чтобы убрать щелчки на старте/конце.
    const fade = Math.min(1, t * 4, (durationSeconds - t) * 4);
    const sample = Math.sin(2 * Math.PI * frequency * t) * 0.3 * Math.max(0, fade);
    buffer.writeInt16LE(Math.round(sample * 32767), 44 + i * 2);
  }

  return buffer;
}

const bgmPath = path.join(publicAudioDir, 'bgm.wav');
const voicePath = path.join(publicAudioDir, 'voice.wav');
writeFileSync(bgmPath, createToneWav({ durationSeconds: 12, frequency: 220 }));
writeFileSync(voicePath, createToneWav({ durationSeconds: 7, frequency: 440 }));
console.log('[audio] bgm.wav', statSync(bgmPath).size, 'bytes; voice.wav', statSync(voicePath).size, 'bytes');

// Tailwind-утилиты, использованные в сцене.
console.log('[audio] compiling tailwind utilities...');
const source = readFileSync(sceneFile, 'utf8');
const tailwind = await postcss([
  tailwindcss({ content: [{ raw: source, extension: 'tsx' }] }),
]).process('@tailwind base;@tailwind components;@tailwind utilities;', { from: undefined });

writeFileSync(
  path.join(generatedDir, 'audio-scene.ts'),
  `// AUTO-GENERATED by render/render-audio.mjs. Do not edit.\n` +
    `export const source = ${JSON.stringify(source)};\n` +
    `export const css = ${JSON.stringify(tailwind.css)};\n`,
);
console.log('[audio] css bytes:', tailwind.css.length);

console.log('[audio] bundling...');
const serveUrl = await bundle({
  entryPoint: path.join(here, 'entry-audio.tsx'),
  publicDir: path.join(here, 'public'),
  outDir: path.join(here, 'bundle-audio'),
  onProgress: (progress) => process.stdout.write(`\r[audio] bundling ${progress}%   `),
});
console.log('\n[audio] bundle ready');

const browserExecutable = [
  process.env.REMOTION_BROWSER,
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
].find((candidate) => candidate && existsSync(candidate));
if (!browserExecutable) throw new Error('Chrome not found. Set REMOTION_BROWSER.');

const composition = await selectComposition({ serveUrl, id: 'AudioDucking', browserExecutable });
console.log('[audio] composition:', composition.id, composition.width, 'x', composition.height);

for (const frame of STILL_FRAMES) {
  const output = path.join(outDir, `audio-frame-${String(frame).padStart(3, '0')}.png`);
  await renderStill({ serveUrl, composition, output, frame, browserExecutable });
  console.log('[audio] still', frame, '->', statSync(output).size, 'bytes');
}

const videoPath = path.join(outDir, 'audio-ducking.mp4');
await renderMedia({
  serveUrl,
  composition,
  codec: 'h264',
  outputLocation: videoPath,
  browserExecutable,
  onProgress: ({ progress }) =>
    process.stdout.write(`\r[audio] video ${Math.round(progress * 100)}%   `),
});
console.log('\n[audio] video:', videoPath, statSync(videoPath).size, 'bytes');
console.log('[audio] DONE');
