import path from 'node:path';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { compileTailwindCss } from './tailwind-v4.mjs';
import { bundle } from '@remotion/bundler';
import { renderMedia, renderStill, selectComposition } from '@remotion/renderer';

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, '..');
const catalogFile = process.argv[2]
  ? path.resolve(projectRoot, process.argv[2])
  : path.join(projectRoot, 'examples', 'vidora-widgets.json');
const generatedDir = path.join(here, '.generated');
const publicDir = path.join(here, 'public');
const outDir = path.join(here, 'out');

const STILL_FRAMES = [30, 60, 130, 230];

if (!existsSync(catalogFile)) throw new Error(`Catalog not found: ${catalogFile}`);
for (const dir of [generatedDir, publicDir, outDir]) mkdirSync(dir, { recursive: true });

const catalog = JSON.parse(readFileSync(catalogFile, 'utf8'));
if (!Array.isArray(catalog.widgets) || catalog.widgets.length === 0) {
  throw new Error('Catalog contains no widgets.');
}
console.log('[widgets] catalog:', path.relative(projectRoot, catalogFile));
console.log('[widgets] widgets found:', catalog.widgets.map((w) => w.id).join(', '));

// 0. Кладём каталог в сгенерированный модуль (entry не зависит от конкретного файла).
writeFileSync(
  path.join(generatedDir, 'widgets-catalog.ts'),
  `// AUTO-GENERATED by render/render-widgets.mjs. Do not edit.\n` +
    `export const catalog = ${JSON.stringify(catalog)};\n`,
);

// 1. Собираем все Tailwind-классы из tsx_code всех виджетов.
console.log('[widgets] compiling tailwind utilities...');
const combinedSource = catalog.widgets.map((w) => w.tsx_code).join('\n');
const tailwindCss = await compileTailwindCss(combinedSource);

writeFileSync(
  path.join(generatedDir, 'widgets-css.ts'),
  `// AUTO-GENERATED by render/render-widgets.mjs. Do not edit.\n` +
    `export const css = ${JSON.stringify(tailwindCss)};\n`,
);
console.log('[widgets] css bytes:', tailwindCss.length);

// 2. Бандлим Remotion-проект, где песочница компилирует виджеты из JSON.
console.log('[widgets] bundling...');
const serveUrl = await bundle({
  entryPoint: path.join(here, 'entry-widgets.tsx'),
  publicDir,
  outDir: path.join(here, 'bundle-widgets'),
  onProgress: (progress) => process.stdout.write(`\r[widgets] bundling ${progress}%   `),
});
console.log('\n[widgets] bundle ready');

const browserExecutable = [
  process.env.REMOTION_BROWSER,
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
].find((candidate) => candidate && existsSync(candidate));
if (!browserExecutable) throw new Error('Chrome not found. Set REMOTION_BROWSER.');

// 3. Рендерим кадры для каждого виджета.
for (const widget of catalog.widgets) {
  const composition = await selectComposition({ serveUrl, id: widget.id, browserExecutable });
  console.log(
    `[widgets] ${widget.id}: ${composition.width}x${composition.height}, ${composition.durationInFrames} frames`,
  );

  for (const frame of STILL_FRAMES) {
    const output = path.join(outDir, `widget-${widget.id}-${String(frame).padStart(3, '0')}.png`);
    await renderStill({ serveUrl, composition, output, frame, browserExecutable });
    console.log(`[widgets]   frame ${frame} -> ${statSync(output).size} bytes`);
  }
}

// 4. Короткий клип для 16:9.
const firstId = catalog.widgets[0].id;
const clipComposition = await selectComposition({ serveUrl, id: firstId, browserExecutable });
const clipPath = path.join(outDir, `widget-${firstId}.mp4`);
console.log('[widgets] rendering clip for', firstId, '...');
await renderMedia({
  serveUrl,
  composition: clipComposition,
  codec: 'h264',
  outputLocation: clipPath,
  frameRange: [0, 120],
  browserExecutable,
  onProgress: ({ progress }) =>
    process.stdout.write(`\r[widgets] clip ${Math.round(progress * 100)}%   `),
});
console.log('\n[widgets] clip:', clipPath, statSync(clipPath).size, 'bytes');
console.log('[widgets] DONE');
