import path from 'node:path';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import { bundle } from '@remotion/bundler';
import { renderStill, selectComposition } from '@remotion/renderer';

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, '..');
const catalogFile = process.argv[2]
  ? path.resolve(projectRoot, process.argv[2])
  : path.join(projectRoot, 'examples', 'vidora-widgets-logo.json');
const generatedDir = path.join(here, '.generated');
const publicDir = path.join(here, 'public');
const publicAssets = path.join(publicDir, 'assets');
const outDir = path.join(here, 'out');

const RENDER_FRAME = 90;

// Набор вариаций пропсов для одного виджета: доказывает, что параметры
// действительно меняют рендер, а картинка корректно парсится и встраивается.
const VARIANTS = [
  { id: 'PropsDefault', props: {} },
  {
    id: 'PropsRedSmall',
    props: {
      logoText: 'VID',
      size: 240,
      logoColor: '#ff5555',
      badgeBgColor: '#4a0000',
      badgeBgGradEnd: '#150000',
      glowColor: '#ff0000',
      sheenFrequency: 1,
      animation: 'cyber-drop',
    },
  },
  {
    id: 'PropsGreenBig',
    props: {
      logoText: 'ORA',
      size: 520,
      logoColor: '#55ff99',
      badgeBgColor: '#003a1a',
      badgeBgGradEnd: '#001108',
      glowColor: '#00ff66',
      sheenFrequency: 1,
      animation: 'smooth-fade',
    },
  },
  { id: 'PropsImage', props: { imageUrl: 'asset:assets/logo-test.svg' } },
  { id: 'PropsIcon', props: { iconName: 'Play', logoColor: '#ffcc00' } },
];

if (!existsSync(catalogFile)) throw new Error(`Catalog not found: ${catalogFile}`);
for (const dir of [generatedDir, publicAssets, outDir]) mkdirSync(dir, { recursive: true });

const catalog = JSON.parse(readFileSync(catalogFile, 'utf8'));
const widget = catalog.widgets?.[0];
if (!widget) throw new Error('Catalog contains no widgets.');
console.log('[props] widget:', widget.id);

// Тестовое изображение (SVG) для варианта imageUrl.
writeFileSync(
  path.join(publicAssets, 'logo-test.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240" viewBox="0 0 240 240">
  <rect width="240" height="240" rx="40" fill="#ff00ff"/>
  <text x="120" y="152" font-family="Arial" font-size="120" font-weight="bold" text-anchor="middle" fill="#ffffff">V</text>
</svg>`,
);

// Tailwind-классы виджета.
const tailwind = await postcss([
  tailwindcss({ content: [{ raw: widget.tsx_code, extension: 'tsx' }] }),
]).process('@tailwind base;@tailwind components;@tailwind utilities;', { from: undefined });
writeFileSync(
  path.join(generatedDir, 'props-css.ts'),
  `// AUTO-GENERATED by render/render-props.mjs. Do not edit.\n` +
    `export const css = ${JSON.stringify(tailwind.css)};\n`,
);

const variantsModule =
  `// AUTO-GENERATED by render/render-props.mjs. Do not edit.\n` +
  `export const variants = ${JSON.stringify(
    VARIANTS.map((v) => ({ id: v.id, code: widget.tsx_code, props: v.props })),
  )};\n`;
writeFileSync(path.join(generatedDir, 'props-variants.ts'), variantsModule);
console.log('[props] variants:', VARIANTS.map((v) => v.id).join(', '));

console.log('[props] bundling...');
const serveUrl = await bundle({
  entryPoint: path.join(here, 'entry-props.tsx'),
  publicDir,
  outDir: path.join(here, 'bundle-props'),
  onProgress: (progress) => process.stdout.write(`\r[props] bundling ${progress}%   `),
});
console.log('\n[props] bundle ready');

const browserExecutable = [
  process.env.REMOTION_BROWSER,
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
].find((candidate) => candidate && existsSync(candidate));
if (!browserExecutable) throw new Error('Chrome not found. Set REMOTION_BROWSER.');

for (const variant of VARIANTS) {
  const composition = await selectComposition({ serveUrl, id: variant.id, browserExecutable });
  const output = path.join(outDir, `props-${variant.id}.png`);
  await renderStill({ serveUrl, composition, output, frame: RENDER_FRAME, browserExecutable });
  console.log('[props]', variant.id, '->', statSync(output).size, 'bytes');
}

console.log('[props] DONE');
