import path from 'node:path';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import { compileTailwindCss } from './tailwind-v4.mjs';
import { bundle } from '@remotion/bundler';
import { renderMedia, renderStill, selectComposition } from '@remotion/renderer';

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, '..');
const exampleFile = path.join(projectRoot, 'examples', 'remotion-scene.tsx');
const generatedDir = path.join(here, '.generated');
const publicDir = path.join(here, 'public');
const brollOutDir = path.join(publicDir, 'b-roll');
const outDir = path.join(here, 'out');

const STILL_FRAMES = [75, 230, 400, 550, 700, 900, 1080];

if (!existsSync(exampleFile)) throw new Error(`Example not found: ${exampleFile}`);
for (const dir of [generatedDir, brollOutDir, outDir]) mkdirSync(dir, { recursive: true });

// 1. Читаем TSX и заменяем локальные абсолютные пути к видео на раздаваемые
//    через Remotion staticFile (аналог ImportResolver из архитектуры).
const original = readFileSync(exampleFile, 'utf8');
const videos = new Map();
const source = original.replace(
  /"((C:\\\\[^"]*?)([^\\/"]+\.mp4))"/g,
  (_full, escaped, _prefix, file) => {
    videos.set(file, escaped.replace(/\\\\/g, '\\'));
    return `{staticFile('b-roll/${file}')}`;
  },
);

if (videos.size === 0) throw new Error('No local video references were rewritten.');

for (const [file, realPath] of videos) {
  if (!existsSync(realPath)) throw new Error(`Video asset missing: ${realPath}`);
  copyFileSync(realPath, path.join(brollOutDir, file));
  console.log('[example] asset:', file, statSync(realPath).size, 'bytes');
}

// 2. Компилируем Tailwind-утилиты, использованные в сцене.
console.log('[example] compiling tailwind utilities...');
const css = await compileTailwindCss(source);

const generatedFile = path.join(generatedDir, 'example-scene.ts');
writeFileSync(
  generatedFile,
  `// AUTO-GENERATED by render/render-example.mjs. Do not edit.\n` +
    `export const source = ${JSON.stringify(source)};\n` +
    `export const css = ${JSON.stringify(css)};\n`,
);
console.log('[example] generated scene module, css:', css.length, 'bytes');

// 3. Бандлим Remotion-проект, внутри которого песочница компилирует сцену.
console.log('[example] bundling...');
const serveUrl = await bundle({
  entryPoint: path.join(here, 'entry-example.tsx'),
  publicDir,
  outDir: path.join(here, 'bundle-example'),
  onProgress: (progress) => process.stdout.write(`\r[example] bundling ${progress}%   `),
});
console.log('\n[example] bundle ready');

const browserExecutable = [
  process.env.REMOTION_BROWSER,
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
].find((candidate) => candidate && existsSync(candidate));
if (!browserExecutable) throw new Error('Chrome not found. Set REMOTION_BROWSER.');

const composition = await selectComposition({ serveUrl, id: 'ExampleScene', browserExecutable });
console.log('[example] composition:', composition.id, composition.width, 'x', composition.height);

// 4. Рендерим ключевые кадры каждого фрагмента.
for (const frame of STILL_FRAMES) {
  const output = path.join(outDir, `example-frame-${String(frame).padStart(4, '0')}.png`);
  await renderStill({ serveUrl, composition, output, frame, browserExecutable });
  console.log('[example] still frame', frame, '->', statSync(output).size, 'bytes');
}

// 5. Рендерим короткий видеоклип (фрагмент 2: глобальная карта).
const clipPath = path.join(outDir, 'example-map.mp4');
console.log('[example] rendering short clip (frames 180-270)...');
await renderMedia({
  serveUrl,
  composition,
  codec: 'h264',
  outputLocation: clipPath,
  frameRange: [180, 270],
  browserExecutable,
  onProgress: ({ progress }) =>
    process.stdout.write(`\r[example] clip ${Math.round(progress * 100)}%   `),
});
console.log('\n[example] clip:', clipPath, statSync(clipPath).size, 'bytes');
console.log('[example] DONE');
