export { SandboxFacade } from './facade';
export { useLiveSandbox } from './react/useLiveSandbox';
export { ModuleCache } from './library-manager/cache';
export { loadMissingModules } from './library-manager/loader';
export type { ModuleImporter } from './library-manager/loader';
export { extractBareImports } from './compiler/analyzer';
export { compileTsx } from './compiler/transform';
export { executeComponent } from './sandbox/evaluator';
export { getShadowedGlobals } from './sandbox/scope';
export { extractAssetZip, createAssetUrlMap, releaseAssetUrls } from './assets/zip';
export type { AssetArchive } from './assets/zip';
export * from './core/types';
export * from './core/errors';
